import { z } from 'zod';
export declare const opportunityBaseSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    title: z.ZodString;
    description: z.ZodString;
    url: z.ZodString;
    organization: z.ZodOptional<z.ZodString>;
    deadline: z.ZodOptional<z.ZodDate>;
    amount: z.ZodOptional<z.ZodString>;
    location: z.ZodOptional<z.ZodString>;
    type: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    category: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    geographicScope: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    durationType: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    targetDemographic: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    artDisciplines: z.ZodOptional<z.ZodArray<z.ZodEnum<[string, ...string[]]>, "many">>;
    requirements: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    tags: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    applicationUrl: z.ZodOptional<z.ZodString>;
    contactEmail: z.ZodOptional<z.ZodString>;
    discoverySource: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    scrapingMethod: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    rawContent: z.ZodOptional<z.ZodString>;
    relevanceScore: z.ZodOptional<z.ZodNumber>;
    validationStatus: z.ZodDefault<z.ZodEnum<[string, ...string[]]>>;
    scrapedAt: z.ZodOptional<z.ZodDate>;
    createdAt: z.ZodOptional<z.ZodDate>;
    updatedAt: z.ZodOptional<z.ZodDate>;
    publishedAt: z.ZodOptional<z.ZodDate>;
}, "strip", z.ZodTypeAny, {
    url: string;
    title: string;
    description: string;
    validationStatus: string;
    type?: string | undefined;
    id?: string | undefined;
    createdAt?: Date | undefined;
    updatedAt?: Date | undefined;
    tags?: string[] | undefined;
    amount?: string | undefined;
    organization?: string | undefined;
    deadline?: Date | undefined;
    location?: string | undefined;
    category?: string | undefined;
    geographicScope?: string | undefined;
    durationType?: string | undefined;
    targetDemographic?: string | undefined;
    artDisciplines?: string[] | undefined;
    requirements?: string[] | undefined;
    applicationUrl?: string | undefined;
    contactEmail?: string | undefined;
    discoverySource?: string | undefined;
    scrapingMethod?: string | undefined;
    rawContent?: string | undefined;
    relevanceScore?: number | undefined;
    scrapedAt?: Date | undefined;
    publishedAt?: Date | undefined;
}, {
    url: string;
    title: string;
    description: string;
    type?: string | undefined;
    id?: string | undefined;
    createdAt?: Date | undefined;
    updatedAt?: Date | undefined;
    tags?: string[] | undefined;
    amount?: string | undefined;
    organization?: string | undefined;
    deadline?: Date | undefined;
    location?: string | undefined;
    category?: string | undefined;
    geographicScope?: string | undefined;
    durationType?: string | undefined;
    targetDemographic?: string | undefined;
    artDisciplines?: string[] | undefined;
    requirements?: string[] | undefined;
    applicationUrl?: string | undefined;
    contactEmail?: string | undefined;
    discoverySource?: string | undefined;
    scrapingMethod?: string | undefined;
    rawContent?: string | undefined;
    relevanceScore?: number | undefined;
    validationStatus?: string | undefined;
    scrapedAt?: Date | undefined;
    publishedAt?: Date | undefined;
}>;
export declare const scrapedOpportunitySchema: z.ZodObject<{
    title: z.ZodString;
    description: z.ZodString;
    url: z.ZodString;
    organization: z.ZodOptional<z.ZodString>;
    deadline: z.ZodOptional<z.ZodDate>;
    amount: z.ZodOptional<z.ZodString>;
    location: z.ZodOptional<z.ZodString>;
    requirements: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    category: z.ZodOptional<z.ZodString>;
    tags: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    applicationUrl: z.ZodOptional<z.ZodString>;
    contactEmail: z.ZodOptional<z.ZodString>;
    rawContent: z.ZodString;
    scrapingMethod: z.ZodEnum<["firecrawl", "playwright", "cheerio"]>;
    scrapedAt: z.ZodDate;
    success: z.ZodBoolean;
    error: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    url: string;
    title: string;
    description: string;
    success: boolean;
    scrapingMethod: "firecrawl" | "playwright" | "cheerio";
    rawContent: string;
    scrapedAt: Date;
    error?: string | undefined;
    tags?: string[] | undefined;
    amount?: string | undefined;
    organization?: string | undefined;
    deadline?: Date | undefined;
    location?: string | undefined;
    category?: string | undefined;
    requirements?: string[] | undefined;
    applicationUrl?: string | undefined;
    contactEmail?: string | undefined;
}, {
    url: string;
    title: string;
    description: string;
    success: boolean;
    scrapingMethod: "firecrawl" | "playwright" | "cheerio";
    rawContent: string;
    scrapedAt: Date;
    error?: string | undefined;
    tags?: string[] | undefined;
    amount?: string | undefined;
    organization?: string | undefined;
    deadline?: Date | undefined;
    location?: string | undefined;
    category?: string | undefined;
    requirements?: string[] | undefined;
    applicationUrl?: string | undefined;
    contactEmail?: string | undefined;
}>;
export declare const createOpportunitySchema: z.ZodObject<Omit<{
    id: z.ZodOptional<z.ZodString>;
    title: z.ZodString;
    description: z.ZodString;
    url: z.ZodString;
    organization: z.ZodOptional<z.ZodString>;
    deadline: z.ZodOptional<z.ZodDate>;
    amount: z.ZodOptional<z.ZodString>;
    location: z.ZodOptional<z.ZodString>;
    type: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    category: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    geographicScope: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    durationType: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    targetDemographic: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    artDisciplines: z.ZodOptional<z.ZodArray<z.ZodEnum<[string, ...string[]]>, "many">>;
    requirements: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    tags: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    applicationUrl: z.ZodOptional<z.ZodString>;
    contactEmail: z.ZodOptional<z.ZodString>;
    discoverySource: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    scrapingMethod: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    rawContent: z.ZodOptional<z.ZodString>;
    relevanceScore: z.ZodOptional<z.ZodNumber>;
    validationStatus: z.ZodDefault<z.ZodEnum<[string, ...string[]]>>;
    scrapedAt: z.ZodOptional<z.ZodDate>;
    createdAt: z.ZodOptional<z.ZodDate>;
    updatedAt: z.ZodOptional<z.ZodDate>;
    publishedAt: z.ZodOptional<z.ZodDate>;
}, "id" | "createdAt" | "updatedAt">, "strip", z.ZodTypeAny, {
    url: string;
    title: string;
    description: string;
    validationStatus: string;
    type?: string | undefined;
    tags?: string[] | undefined;
    amount?: string | undefined;
    organization?: string | undefined;
    deadline?: Date | undefined;
    location?: string | undefined;
    category?: string | undefined;
    geographicScope?: string | undefined;
    durationType?: string | undefined;
    targetDemographic?: string | undefined;
    artDisciplines?: string[] | undefined;
    requirements?: string[] | undefined;
    applicationUrl?: string | undefined;
    contactEmail?: string | undefined;
    discoverySource?: string | undefined;
    scrapingMethod?: string | undefined;
    rawContent?: string | undefined;
    relevanceScore?: number | undefined;
    scrapedAt?: Date | undefined;
    publishedAt?: Date | undefined;
}, {
    url: string;
    title: string;
    description: string;
    type?: string | undefined;
    tags?: string[] | undefined;
    amount?: string | undefined;
    organization?: string | undefined;
    deadline?: Date | undefined;
    location?: string | undefined;
    category?: string | undefined;
    geographicScope?: string | undefined;
    durationType?: string | undefined;
    targetDemographic?: string | undefined;
    artDisciplines?: string[] | undefined;
    requirements?: string[] | undefined;
    applicationUrl?: string | undefined;
    contactEmail?: string | undefined;
    discoverySource?: string | undefined;
    scrapingMethod?: string | undefined;
    rawContent?: string | undefined;
    relevanceScore?: number | undefined;
    validationStatus?: string | undefined;
    scrapedAt?: Date | undefined;
    publishedAt?: Date | undefined;
}>;
export declare const updateOpportunitySchema: z.ZodObject<Omit<{
    id: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    title: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
    url: z.ZodOptional<z.ZodString>;
    organization: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    deadline: z.ZodOptional<z.ZodOptional<z.ZodDate>>;
    amount: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    location: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    type: z.ZodOptional<z.ZodOptional<z.ZodEnum<[string, ...string[]]>>>;
    category: z.ZodOptional<z.ZodOptional<z.ZodEnum<[string, ...string[]]>>>;
    geographicScope: z.ZodOptional<z.ZodOptional<z.ZodEnum<[string, ...string[]]>>>;
    durationType: z.ZodOptional<z.ZodOptional<z.ZodEnum<[string, ...string[]]>>>;
    targetDemographic: z.ZodOptional<z.ZodOptional<z.ZodEnum<[string, ...string[]]>>>;
    artDisciplines: z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodEnum<[string, ...string[]]>, "many">>>;
    requirements: z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodString, "many">>>;
    tags: z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodString, "many">>>;
    applicationUrl: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    contactEmail: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    discoverySource: z.ZodOptional<z.ZodOptional<z.ZodEnum<[string, ...string[]]>>>;
    scrapingMethod: z.ZodOptional<z.ZodOptional<z.ZodEnum<[string, ...string[]]>>>;
    rawContent: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    relevanceScore: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    validationStatus: z.ZodOptional<z.ZodDefault<z.ZodEnum<[string, ...string[]]>>>;
    scrapedAt: z.ZodOptional<z.ZodOptional<z.ZodDate>>;
    createdAt: z.ZodOptional<z.ZodOptional<z.ZodDate>>;
    updatedAt: z.ZodOptional<z.ZodOptional<z.ZodDate>>;
    publishedAt: z.ZodOptional<z.ZodOptional<z.ZodDate>>;
}, "id" | "createdAt">, "strip", z.ZodTypeAny, {
    type?: string | undefined;
    updatedAt?: Date | undefined;
    url?: string | undefined;
    title?: string | undefined;
    description?: string | undefined;
    tags?: string[] | undefined;
    amount?: string | undefined;
    organization?: string | undefined;
    deadline?: Date | undefined;
    location?: string | undefined;
    category?: string | undefined;
    geographicScope?: string | undefined;
    durationType?: string | undefined;
    targetDemographic?: string | undefined;
    artDisciplines?: string[] | undefined;
    requirements?: string[] | undefined;
    applicationUrl?: string | undefined;
    contactEmail?: string | undefined;
    discoverySource?: string | undefined;
    scrapingMethod?: string | undefined;
    rawContent?: string | undefined;
    relevanceScore?: number | undefined;
    validationStatus?: string | undefined;
    scrapedAt?: Date | undefined;
    publishedAt?: Date | undefined;
}, {
    type?: string | undefined;
    updatedAt?: Date | undefined;
    url?: string | undefined;
    title?: string | undefined;
    description?: string | undefined;
    tags?: string[] | undefined;
    amount?: string | undefined;
    organization?: string | undefined;
    deadline?: Date | undefined;
    location?: string | undefined;
    category?: string | undefined;
    geographicScope?: string | undefined;
    durationType?: string | undefined;
    targetDemographic?: string | undefined;
    artDisciplines?: string[] | undefined;
    requirements?: string[] | undefined;
    applicationUrl?: string | undefined;
    contactEmail?: string | undefined;
    discoverySource?: string | undefined;
    scrapingMethod?: string | undefined;
    rawContent?: string | undefined;
    relevanceScore?: number | undefined;
    validationStatus?: string | undefined;
    scrapedAt?: Date | undefined;
    publishedAt?: Date | undefined;
}>;
export declare const opportunitySearchSchema: z.ZodObject<{
    query: z.ZodOptional<z.ZodString>;
    title: z.ZodOptional<z.ZodString>;
    organization: z.ZodOptional<z.ZodString>;
    type: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    category: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    location: z.ZodOptional<z.ZodString>;
    geographicScope: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    artDisciplines: z.ZodOptional<z.ZodArray<z.ZodEnum<[string, ...string[]]>, "many">>;
    tags: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    minAmount: z.ZodOptional<z.ZodNumber>;
    maxAmount: z.ZodOptional<z.ZodNumber>;
    deadlineAfter: z.ZodOptional<z.ZodDate>;
    deadlineBefore: z.ZodOptional<z.ZodDate>;
    minRelevanceScore: z.ZodOptional<z.ZodNumber>;
    maxRelevanceScore: z.ZodOptional<z.ZodNumber>;
    validationStatus: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    discoverySource: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    createdAfter: z.ZodOptional<z.ZodDate>;
    createdBefore: z.ZodOptional<z.ZodDate>;
    page: z.ZodDefault<z.ZodNumber>;
    limit: z.ZodDefault<z.ZodNumber>;
    sortBy: z.ZodDefault<z.ZodEnum<["createdAt", "deadline", "relevanceScore", "title", "amount"]>>;
    sortOrder: z.ZodDefault<z.ZodEnum<["asc", "desc"]>>;
}, "strip", z.ZodTypeAny, {
    page: number;
    limit: number;
    sortBy: "createdAt" | "title" | "amount" | "deadline" | "relevanceScore";
    sortOrder: "asc" | "desc";
    query?: string | undefined;
    type?: string | undefined;
    title?: string | undefined;
    tags?: string[] | undefined;
    organization?: string | undefined;
    location?: string | undefined;
    category?: string | undefined;
    geographicScope?: string | undefined;
    artDisciplines?: string[] | undefined;
    discoverySource?: string | undefined;
    validationStatus?: string | undefined;
    minAmount?: number | undefined;
    maxAmount?: number | undefined;
    deadlineAfter?: Date | undefined;
    deadlineBefore?: Date | undefined;
    minRelevanceScore?: number | undefined;
    maxRelevanceScore?: number | undefined;
    createdAfter?: Date | undefined;
    createdBefore?: Date | undefined;
}, {
    query?: string | undefined;
    type?: string | undefined;
    title?: string | undefined;
    page?: number | undefined;
    limit?: number | undefined;
    sortBy?: "createdAt" | "title" | "amount" | "deadline" | "relevanceScore" | undefined;
    sortOrder?: "asc" | "desc" | undefined;
    tags?: string[] | undefined;
    organization?: string | undefined;
    location?: string | undefined;
    category?: string | undefined;
    geographicScope?: string | undefined;
    artDisciplines?: string[] | undefined;
    discoverySource?: string | undefined;
    validationStatus?: string | undefined;
    minAmount?: number | undefined;
    maxAmount?: number | undefined;
    deadlineAfter?: Date | undefined;
    deadlineBefore?: Date | undefined;
    minRelevanceScore?: number | undefined;
    maxRelevanceScore?: number | undefined;
    createdAfter?: Date | undefined;
    createdBefore?: Date | undefined;
}>;
export declare const opportunityApplicationSchema: z.ZodObject<{
    opportunityId: z.ZodString;
    profileId: z.ZodString;
    status: z.ZodEnum<[string, ...string[]]>;
    appliedAt: z.ZodOptional<z.ZodDate>;
    submittedAt: z.ZodOptional<z.ZodDate>;
    responseAt: z.ZodOptional<z.ZodDate>;
    notes: z.ZodOptional<z.ZodString>;
    applicationData: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>;
}, "strip", z.ZodTypeAny, {
    status: string;
    opportunityId: string;
    profileId: string;
    appliedAt?: Date | undefined;
    submittedAt?: Date | undefined;
    responseAt?: Date | undefined;
    notes?: string | undefined;
    applicationData?: Record<string, any> | undefined;
}, {
    status: string;
    opportunityId: string;
    profileId: string;
    appliedAt?: Date | undefined;
    submittedAt?: Date | undefined;
    responseAt?: Date | undefined;
    notes?: string | undefined;
    applicationData?: Record<string, any> | undefined;
}>;
export declare const opportunityAnalysisSchema: z.ZodObject<{
    opportunityId: z.ZodString;
    profileId: z.ZodString;
    relevanceScore: z.ZodNumber;
    matchingCriteria: z.ZodArray<z.ZodString, "many">;
    strengthsAlignment: z.ZodArray<z.ZodString, "many">;
    gapsIdentified: z.ZodArray<z.ZodString, "many">;
    recommendedActions: z.ZodArray<z.ZodString, "many">;
    confidenceLevel: z.ZodNumber;
    analysisDate: z.ZodDate;
    aiModel: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    relevanceScore: number;
    opportunityId: string;
    profileId: string;
    matchingCriteria: string[];
    strengthsAlignment: string[];
    gapsIdentified: string[];
    recommendedActions: string[];
    confidenceLevel: number;
    analysisDate: Date;
    aiModel?: string | undefined;
}, {
    relevanceScore: number;
    opportunityId: string;
    profileId: string;
    matchingCriteria: string[];
    strengthsAlignment: string[];
    gapsIdentified: string[];
    recommendedActions: string[];
    confidenceLevel: number;
    analysisDate: Date;
    aiModel?: string | undefined;
}>;
export declare const bulkOpportunityOperationSchema: z.ZodObject<{
    opportunityIds: z.ZodArray<z.ZodString, "many">;
    operation: z.ZodEnum<["validate", "archive", "delete", "reprocess"]>;
    options: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>;
}, "strip", z.ZodTypeAny, {
    operation: "delete" | "archive" | "validate" | "reprocess";
    opportunityIds: string[];
    options?: Record<string, any> | undefined;
}, {
    operation: "delete" | "archive" | "validate" | "reprocess";
    opportunityIds: string[];
    options?: Record<string, any> | undefined;
}>;
export declare const opportunityImportSchema: z.ZodObject<{
    source: z.ZodString;
    format: z.ZodEnum<["json", "csv", "xml"]>;
    data: z.ZodArray<z.ZodRecord<z.ZodString, z.ZodAny>, "many">;
    options: z.ZodOptional<z.ZodObject<{
        skipDuplicates: z.ZodDefault<z.ZodBoolean>;
        validateFirst: z.ZodDefault<z.ZodBoolean>;
        assignToProfile: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        skipDuplicates: boolean;
        validateFirst: boolean;
        assignToProfile?: string | undefined;
    }, {
        skipDuplicates?: boolean | undefined;
        validateFirst?: boolean | undefined;
        assignToProfile?: string | undefined;
    }>>;
}, "strip", z.ZodTypeAny, {
    data: Record<string, any>[];
    source: string;
    format: "json" | "csv" | "xml";
    options?: {
        skipDuplicates: boolean;
        validateFirst: boolean;
        assignToProfile?: string | undefined;
    } | undefined;
}, {
    data: Record<string, any>[];
    source: string;
    format: "json" | "csv" | "xml";
    options?: {
        skipDuplicates?: boolean | undefined;
        validateFirst?: boolean | undefined;
        assignToProfile?: string | undefined;
    } | undefined;
}>;
export declare const opportunityStatsSchema: z.ZodObject<{
    total: z.ZodNumber;
    byType: z.ZodRecord<z.ZodString, z.ZodNumber>;
    byCategory: z.ZodRecord<z.ZodString, z.ZodNumber>;
    byValidationStatus: z.ZodRecord<z.ZodString, z.ZodNumber>;
    byRelevanceRange: z.ZodRecord<z.ZodString, z.ZodNumber>;
    averageRelevanceScore: z.ZodNumber;
    recentlyAdded: z.ZodNumber;
    upcomingDeadlines: z.ZodNumber;
}, "strip", z.ZodTypeAny, {
    total: number;
    byType: Record<string, number>;
    byCategory: Record<string, number>;
    byValidationStatus: Record<string, number>;
    byRelevanceRange: Record<string, number>;
    averageRelevanceScore: number;
    recentlyAdded: number;
    upcomingDeadlines: number;
}, {
    total: number;
    byType: Record<string, number>;
    byCategory: Record<string, number>;
    byValidationStatus: Record<string, number>;
    byRelevanceRange: Record<string, number>;
    averageRelevanceScore: number;
    recentlyAdded: number;
    upcomingDeadlines: number;
}>;
export type OpportunityBase = z.infer<typeof opportunityBaseSchema>;
export type ScrapedOpportunity = z.infer<typeof scrapedOpportunitySchema>;
export type CreateOpportunity = z.infer<typeof createOpportunitySchema>;
export type UpdateOpportunity = z.infer<typeof updateOpportunitySchema>;
export type OpportunitySearch = z.infer<typeof opportunitySearchSchema>;
export type OpportunityApplication = z.infer<typeof opportunityApplicationSchema>;
export type OpportunityAnalysis = z.infer<typeof opportunityAnalysisSchema>;
export type BulkOpportunityOperation = z.infer<typeof bulkOpportunityOperationSchema>;
export type OpportunityImport = z.infer<typeof opportunityImportSchema>;
export type OpportunityStats = z.infer<typeof opportunityStatsSchema>;
//# sourceMappingURL=opportunity.schemas.d.ts.map