import { z } from 'zod';
export declare const opportunityBaseSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    title: z.ZodString;
    description: z.ZodString;
    url: z.ZodString;
    organization: z.ZodOptional<z.ZodString>;
    deadline: z.ZodOptional<z.ZodDate>;
    amount: z.ZodOptional<z.ZodString>;
    location: z.ZodOptional<z.ZodString>;
    type: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    category: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    geographicScope: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    durationType: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    targetDemographic: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    artDisciplines: z.ZodOptional<z.ZodArray<z.ZodEnum<[string, ...string[]]>, "many">>;
    requirements: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    tags: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    applicationUrl: z.ZodOptional<z.ZodString>;
    contactEmail: z.ZodOptional<z.ZodString>;
    discoverySource: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    scrapingMethod: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    rawContent: z.ZodOptional<z.ZodString>;
    relevanceScore: z.ZodOptional<z.ZodNumber>;
    validationStatus: z.ZodDefault<z.ZodEnum<[string, ...string[]]>>;
    scrapedAt: z.ZodOptional<z.ZodDate>;
    createdAt: z.ZodOptional<z.ZodDate>;
    updatedAt: z.ZodOptional<z.ZodDate>;
    publishedAt: z.ZodOptional<z.ZodDate>;
}, "strip", z.ZodTypeAny, {
    tags?: string[];
    description?: string;
    id?: string;
    createdAt?: Date;
    updatedAt?: Date;
    type?: string;
    title?: string;
    location?: string;
    relevanceScore?: number;
    url?: string;
    organization?: string;
    deadline?: Date;
    amount?: string;
    category?: string;
    geographicScope?: string;
    durationType?: string;
    targetDemographic?: string;
    artDisciplines?: string[];
    requirements?: string[];
    applicationUrl?: string;
    contactEmail?: string;
    discoverySource?: string;
    scrapingMethod?: string;
    rawContent?: string;
    validationStatus?: string;
    scrapedAt?: Date;
    publishedAt?: Date;
}, {
    tags?: string[];
    description?: string;
    id?: string;
    createdAt?: Date;
    updatedAt?: Date;
    type?: string;
    title?: string;
    location?: string;
    relevanceScore?: number;
    url?: string;
    organization?: string;
    deadline?: Date;
    amount?: string;
    category?: string;
    geographicScope?: string;
    durationType?: string;
    targetDemographic?: string;
    artDisciplines?: string[];
    requirements?: string[];
    applicationUrl?: string;
    contactEmail?: string;
    discoverySource?: string;
    scrapingMethod?: string;
    rawContent?: string;
    validationStatus?: string;
    scrapedAt?: Date;
    publishedAt?: Date;
}>;
export declare const scrapedOpportunitySchema: z.ZodObject<{
    title: z.ZodString;
    description: z.ZodString;
    url: z.ZodString;
    organization: z.ZodOptional<z.ZodString>;
    deadline: z.ZodOptional<z.ZodDate>;
    amount: z.ZodOptional<z.ZodString>;
    location: z.ZodOptional<z.ZodString>;
    requirements: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    category: z.ZodOptional<z.ZodString>;
    tags: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    applicationUrl: z.ZodOptional<z.ZodString>;
    contactEmail: z.ZodOptional<z.ZodString>;
    rawContent: z.ZodString;
    scrapingMethod: z.ZodEnum<["firecrawl", "playwright", "cheerio"]>;
    scrapedAt: z.ZodDate;
    success: z.ZodBoolean;
    error: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    tags?: string[];
    description?: string;
    error?: string;
    title?: string;
    location?: string;
    success?: boolean;
    url?: string;
    organization?: string;
    deadline?: Date;
    amount?: string;
    category?: string;
    requirements?: string[];
    applicationUrl?: string;
    contactEmail?: string;
    scrapingMethod?: "firecrawl" | "playwright" | "cheerio";
    rawContent?: string;
    scrapedAt?: Date;
}, {
    tags?: string[];
    description?: string;
    error?: string;
    title?: string;
    location?: string;
    success?: boolean;
    url?: string;
    organization?: string;
    deadline?: Date;
    amount?: string;
    category?: string;
    requirements?: string[];
    applicationUrl?: string;
    contactEmail?: string;
    scrapingMethod?: "firecrawl" | "playwright" | "cheerio";
    rawContent?: string;
    scrapedAt?: Date;
}>;
export declare const createOpportunitySchema: z.ZodObject<Omit<{
    id: z.ZodOptional<z.ZodString>;
    title: z.ZodString;
    description: z.ZodString;
    url: z.ZodString;
    organization: z.ZodOptional<z.ZodString>;
    deadline: z.ZodOptional<z.ZodDate>;
    amount: z.ZodOptional<z.ZodString>;
    location: z.ZodOptional<z.ZodString>;
    type: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    category: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    geographicScope: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    durationType: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    targetDemographic: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    artDisciplines: z.ZodOptional<z.ZodArray<z.ZodEnum<[string, ...string[]]>, "many">>;
    requirements: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    tags: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    applicationUrl: z.ZodOptional<z.ZodString>;
    contactEmail: z.ZodOptional<z.ZodString>;
    discoverySource: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    scrapingMethod: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    rawContent: z.ZodOptional<z.ZodString>;
    relevanceScore: z.ZodOptional<z.ZodNumber>;
    validationStatus: z.ZodDefault<z.ZodEnum<[string, ...string[]]>>;
    scrapedAt: z.ZodOptional<z.ZodDate>;
    createdAt: z.ZodOptional<z.ZodDate>;
    updatedAt: z.ZodOptional<z.ZodDate>;
    publishedAt: z.ZodOptional<z.ZodDate>;
}, "id" | "createdAt" | "updatedAt">, "strip", z.ZodTypeAny, {
    tags?: string[];
    description?: string;
    type?: string;
    title?: string;
    location?: string;
    relevanceScore?: number;
    url?: string;
    organization?: string;
    deadline?: Date;
    amount?: string;
    category?: string;
    geographicScope?: string;
    durationType?: string;
    targetDemographic?: string;
    artDisciplines?: string[];
    requirements?: string[];
    applicationUrl?: string;
    contactEmail?: string;
    discoverySource?: string;
    scrapingMethod?: string;
    rawContent?: string;
    validationStatus?: string;
    scrapedAt?: Date;
    publishedAt?: Date;
}, {
    tags?: string[];
    description?: string;
    type?: string;
    title?: string;
    location?: string;
    relevanceScore?: number;
    url?: string;
    organization?: string;
    deadline?: Date;
    amount?: string;
    category?: string;
    geographicScope?: string;
    durationType?: string;
    targetDemographic?: string;
    artDisciplines?: string[];
    requirements?: string[];
    applicationUrl?: string;
    contactEmail?: string;
    discoverySource?: string;
    scrapingMethod?: string;
    rawContent?: string;
    validationStatus?: string;
    scrapedAt?: Date;
    publishedAt?: Date;
}>;
export declare const updateOpportunitySchema: z.ZodObject<Omit<{
    id: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    title: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
    url: z.ZodOptional<z.ZodString>;
    organization: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    deadline: z.ZodOptional<z.ZodOptional<z.ZodDate>>;
    amount: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    location: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    type: z.ZodOptional<z.ZodOptional<z.ZodEnum<[string, ...string[]]>>>;
    category: z.ZodOptional<z.ZodOptional<z.ZodEnum<[string, ...string[]]>>>;
    geographicScope: z.ZodOptional<z.ZodOptional<z.ZodEnum<[string, ...string[]]>>>;
    durationType: z.ZodOptional<z.ZodOptional<z.ZodEnum<[string, ...string[]]>>>;
    targetDemographic: z.ZodOptional<z.ZodOptional<z.ZodEnum<[string, ...string[]]>>>;
    artDisciplines: z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodEnum<[string, ...string[]]>, "many">>>;
    requirements: z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodString, "many">>>;
    tags: z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodString, "many">>>;
    applicationUrl: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    contactEmail: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    discoverySource: z.ZodOptional<z.ZodOptional<z.ZodEnum<[string, ...string[]]>>>;
    scrapingMethod: z.ZodOptional<z.ZodOptional<z.ZodEnum<[string, ...string[]]>>>;
    rawContent: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    relevanceScore: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    validationStatus: z.ZodOptional<z.ZodDefault<z.ZodEnum<[string, ...string[]]>>>;
    scrapedAt: z.ZodOptional<z.ZodOptional<z.ZodDate>>;
    createdAt: z.ZodOptional<z.ZodOptional<z.ZodDate>>;
    updatedAt: z.ZodOptional<z.ZodOptional<z.ZodDate>>;
    publishedAt: z.ZodOptional<z.ZodOptional<z.ZodDate>>;
}, "id" | "createdAt">, "strip", z.ZodTypeAny, {
    tags?: string[];
    description?: string;
    updatedAt?: Date;
    type?: string;
    title?: string;
    location?: string;
    relevanceScore?: number;
    url?: string;
    organization?: string;
    deadline?: Date;
    amount?: string;
    category?: string;
    geographicScope?: string;
    durationType?: string;
    targetDemographic?: string;
    artDisciplines?: string[];
    requirements?: string[];
    applicationUrl?: string;
    contactEmail?: string;
    discoverySource?: string;
    scrapingMethod?: string;
    rawContent?: string;
    validationStatus?: string;
    scrapedAt?: Date;
    publishedAt?: Date;
}, {
    tags?: string[];
    description?: string;
    updatedAt?: Date;
    type?: string;
    title?: string;
    location?: string;
    relevanceScore?: number;
    url?: string;
    organization?: string;
    deadline?: Date;
    amount?: string;
    category?: string;
    geographicScope?: string;
    durationType?: string;
    targetDemographic?: string;
    artDisciplines?: string[];
    requirements?: string[];
    applicationUrl?: string;
    contactEmail?: string;
    discoverySource?: string;
    scrapingMethod?: string;
    rawContent?: string;
    validationStatus?: string;
    scrapedAt?: Date;
    publishedAt?: Date;
}>;
export declare const opportunitySearchSchema: z.ZodObject<{
    query: z.ZodOptional<z.ZodString>;
    title: z.ZodOptional<z.ZodString>;
    organization: z.ZodOptional<z.ZodString>;
    type: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    category: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    location: z.ZodOptional<z.ZodString>;
    geographicScope: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    artDisciplines: z.ZodOptional<z.ZodArray<z.ZodEnum<[string, ...string[]]>, "many">>;
    tags: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    minAmount: z.ZodOptional<z.ZodNumber>;
    maxAmount: z.ZodOptional<z.ZodNumber>;
    deadlineAfter: z.ZodOptional<z.ZodDate>;
    deadlineBefore: z.ZodOptional<z.ZodDate>;
    minRelevanceScore: z.ZodOptional<z.ZodNumber>;
    maxRelevanceScore: z.ZodOptional<z.ZodNumber>;
    validationStatus: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    discoverySource: z.ZodOptional<z.ZodEnum<[string, ...string[]]>>;
    createdAfter: z.ZodOptional<z.ZodDate>;
    createdBefore: z.ZodOptional<z.ZodDate>;
    page: z.ZodDefault<z.ZodNumber>;
    limit: z.ZodDefault<z.ZodNumber>;
    sortBy: z.ZodDefault<z.ZodEnum<["createdAt", "deadline", "relevanceScore", "title", "amount"]>>;
    sortOrder: z.ZodDefault<z.ZodEnum<["asc", "desc"]>>;
}, "strip", z.ZodTypeAny, {
    tags?: string[];
    query?: string;
    type?: string;
    title?: string;
    location?: string;
    organization?: string;
    page?: number;
    limit?: number;
    minRelevanceScore?: number;
    deadlineBefore?: Date;
    sortBy?: "createdAt" | "title" | "relevanceScore" | "deadline" | "amount";
    sortOrder?: "asc" | "desc";
    category?: string;
    geographicScope?: string;
    artDisciplines?: string[];
    discoverySource?: string;
    validationStatus?: string;
    minAmount?: number;
    maxAmount?: number;
    deadlineAfter?: Date;
    maxRelevanceScore?: number;
    createdAfter?: Date;
    createdBefore?: Date;
}, {
    tags?: string[];
    query?: string;
    type?: string;
    title?: string;
    location?: string;
    organization?: string;
    page?: number;
    limit?: number;
    minRelevanceScore?: number;
    deadlineBefore?: Date;
    sortBy?: "createdAt" | "title" | "relevanceScore" | "deadline" | "amount";
    sortOrder?: "asc" | "desc";
    category?: string;
    geographicScope?: string;
    artDisciplines?: string[];
    discoverySource?: string;
    validationStatus?: string;
    minAmount?: number;
    maxAmount?: number;
    deadlineAfter?: Date;
    maxRelevanceScore?: number;
    createdAfter?: Date;
    createdBefore?: Date;
}>;
export declare const opportunityApplicationSchema: z.ZodObject<{
    opportunityId: z.ZodString;
    profileId: z.ZodString;
    status: z.ZodEnum<[string, ...string[]]>;
    appliedAt: z.ZodOptional<z.ZodDate>;
    submittedAt: z.ZodOptional<z.ZodDate>;
    responseAt: z.ZodOptional<z.ZodDate>;
    notes: z.ZodOptional<z.ZodString>;
    applicationData: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>;
}, "strip", z.ZodTypeAny, {
    profileId?: string;
    status?: string;
    opportunityId?: string;
    notes?: string;
    appliedAt?: Date;
    submittedAt?: Date;
    responseAt?: Date;
    applicationData?: Record<string, any>;
}, {
    profileId?: string;
    status?: string;
    opportunityId?: string;
    notes?: string;
    appliedAt?: Date;
    submittedAt?: Date;
    responseAt?: Date;
    applicationData?: Record<string, any>;
}>;
export declare const opportunityAnalysisSchema: z.ZodObject<{
    opportunityId: z.ZodString;
    profileId: z.ZodString;
    relevanceScore: z.ZodNumber;
    matchingCriteria: z.ZodArray<z.ZodString, "many">;
    strengthsAlignment: z.ZodArray<z.ZodString, "many">;
    gapsIdentified: z.ZodArray<z.ZodString, "many">;
    recommendedActions: z.ZodArray<z.ZodString, "many">;
    confidenceLevel: z.ZodNumber;
    analysisDate: z.ZodDate;
    aiModel: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    profileId?: string;
    opportunityId?: string;
    relevanceScore?: number;
    matchingCriteria?: string[];
    aiModel?: string;
    strengthsAlignment?: string[];
    gapsIdentified?: string[];
    recommendedActions?: string[];
    confidenceLevel?: number;
    analysisDate?: Date;
}, {
    profileId?: string;
    opportunityId?: string;
    relevanceScore?: number;
    matchingCriteria?: string[];
    aiModel?: string;
    strengthsAlignment?: string[];
    gapsIdentified?: string[];
    recommendedActions?: string[];
    confidenceLevel?: number;
    analysisDate?: Date;
}>;
export declare const bulkOpportunityOperationSchema: z.ZodObject<{
    opportunityIds: z.ZodArray<z.ZodString, "many">;
    operation: z.ZodEnum<["validate", "archive", "delete", "reprocess"]>;
    options: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>;
}, "strip", z.ZodTypeAny, {
    options?: Record<string, any>;
    operation?: "delete" | "archive" | "validate" | "reprocess";
    opportunityIds?: string[];
}, {
    options?: Record<string, any>;
    operation?: "delete" | "archive" | "validate" | "reprocess";
    opportunityIds?: string[];
}>;
export declare const opportunityImportSchema: z.ZodObject<{
    source: z.ZodString;
    format: z.ZodEnum<["json", "csv", "xml"]>;
    data: z.ZodArray<z.ZodRecord<z.ZodString, z.ZodAny>, "many">;
    options: z.ZodOptional<z.ZodObject<{
        skipDuplicates: z.ZodDefault<z.ZodBoolean>;
        validateFirst: z.ZodDefault<z.ZodBoolean>;
        assignToProfile: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        skipDuplicates?: boolean;
        validateFirst?: boolean;
        assignToProfile?: string;
    }, {
        skipDuplicates?: boolean;
        validateFirst?: boolean;
        assignToProfile?: string;
    }>>;
}, "strip", z.ZodTypeAny, {
    format?: "xml" | "json" | "csv";
    data?: Record<string, any>[];
    options?: {
        skipDuplicates?: boolean;
        validateFirst?: boolean;
        assignToProfile?: string;
    };
    source?: string;
}, {
    format?: "xml" | "json" | "csv";
    data?: Record<string, any>[];
    options?: {
        skipDuplicates?: boolean;
        validateFirst?: boolean;
        assignToProfile?: string;
    };
    source?: string;
}>;
export declare const opportunityStatsSchema: z.ZodObject<{
    total: z.ZodNumber;
    byType: z.ZodRecord<z.ZodString, z.ZodNumber>;
    byCategory: z.ZodRecord<z.ZodString, z.ZodNumber>;
    byValidationStatus: z.ZodRecord<z.ZodString, z.ZodNumber>;
    byRelevanceRange: z.ZodRecord<z.ZodString, z.ZodNumber>;
    averageRelevanceScore: z.ZodNumber;
    recentlyAdded: z.ZodNumber;
    upcomingDeadlines: z.ZodNumber;
}, "strip", z.ZodTypeAny, {
    total?: number;
    upcomingDeadlines?: number;
    byType?: Record<string, number>;
    byCategory?: Record<string, number>;
    byValidationStatus?: Record<string, number>;
    byRelevanceRange?: Record<string, number>;
    averageRelevanceScore?: number;
    recentlyAdded?: number;
}, {
    total?: number;
    upcomingDeadlines?: number;
    byType?: Record<string, number>;
    byCategory?: Record<string, number>;
    byValidationStatus?: Record<string, number>;
    byRelevanceRange?: Record<string, number>;
    averageRelevanceScore?: number;
    recentlyAdded?: number;
}>;
export type OpportunityBase = z.infer<typeof opportunityBaseSchema>;
export type ScrapedOpportunity = z.infer<typeof scrapedOpportunitySchema>;
export type CreateOpportunity = z.infer<typeof createOpportunitySchema>;
export type UpdateOpportunity = z.infer<typeof updateOpportunitySchema>;
export type OpportunitySearch = z.infer<typeof opportunitySearchSchema>;
export type OpportunityApplication = z.infer<typeof opportunityApplicationSchema>;
export type OpportunityAnalysis = z.infer<typeof opportunityAnalysisSchema>;
export type BulkOpportunityOperation = z.infer<typeof bulkOpportunityOperationSchema>;
export type OpportunityImport = z.infer<typeof opportunityImportSchema>;
export type OpportunityStats = z.infer<typeof opportunityStatsSchema>;
